# ===============================
# CASIS - Configuração de E-mail
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Coloque o e-mail oficial do CA aqui
spring.mail.username=laerciosf04@gmail.com
# Coloque a "Senha de Aplicativo" na conta Google
spring.mail.password=zjfv vwzb akui tqfi

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true