# Mapeia as chaves para buscar do painel de Environment do Render
spring.mail.username=${EMAIL_CASIS}
spring.mail.password=${SENHA_CASIS}
API_SECRET=${API_SECRET}

GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}

# O ID da pasta oficial do CASIS que só existe em Produção
GOOGLE_DRIVE_PASTA_RAIZ_ID=${DRIVE_PASTA_RAIZ_ID}