# perfil ativo em dev
spring.profiles.active=dev

# Configurações universais (não mudam entre ambientes)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=true