# secrets.properties
spring.config.import=optional:file:./secrets.properties

# E-mail de testes (Usar um email teu com uma senha de app provisória)
spring.mail.username=${spring.mail.username}

# Senha de segurança para testar a API localmente no Postman/React
API_SECRET=${API_SECRET}

# Credenciais do Google Drive (Consultar Readme.md)
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}

# ID DA PASTA DE TESTES NO DRIVE (Para não sujar a oficial)
google.drive.pasta.raiz.id=${google.drive.pasta.raiz.id}